export const FETCH_CHAMPIONS = 'FETCH_CHAMPIONS'
export const REQUEST_CHAMPIONS = 'REQUEST_CHAMPIONS'
export const RECEIVE_CHAMPIONS = 'RECEIVE_CHAMPIONS'
export const ERROR_CHAMPIONS = 'ERROR_CHAMPIONS'

export const FETCH_ABILITIES = 'FETCH_ABILITIES'
export const REQUEST_ABILITIES = 'REQUEST_ABILITIES'
export const RECEIVE_ABILITIES = 'RECEIVE_ABILITIES'
export const ERROR_ABILITIES = 'ERROR_ABILITIES'

export const FETCH_BATTLERITES = 'FETCH_BATTLERITES'
export const REQUEST_BATTLERITES = 'REQUEST_BATTLERITES'
export const RECEIVE_BATTLERITES = 'RECEIVE_BATTLERITES'
export const ERROR_BATTLERITES = 'ERROR_BATTLERITES'
