export const FETCH_CHAMPIONS = 'FETCH_CHAMPIONS'
export const REQUEST_CHAMPIONS = 'REQUEST_CHAMPIONS'
export const RECEIVE_CHAMPIONS = 'RECEIVE_CHAMPIONS'
export const ERROR_CHAMPIONS = 'ERROR_CHAMPIONS'
